name = "Costing a Commune"
author = "kristinnsnr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cb100443549be7659901867241d2ef4fd09085fa56530375c7a6c3666d09b8d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
