name = "Costing a Commune"
author = "kristinnsnr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "511a2b33a4cd79b4b8e0968519deee71c93c921c4abce2d38f9a90f59c8fe04a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
