name = "Costing a Commune"
author = "kristinnsnr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d00faad1ddb563208d37a36e9767b8a4102dc964cbb13d500f9218284d7c4413"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.224"
